using System.IO.Compression;
using System.Text;
using Ovi.Sdk.Nodes;
using Ovi.Sdk.Packaging.PublishPipeline;

namespace Ovi.Sdk.Packaging;

/// <summary>
/// Authors <c>.ovipkg</c> packages: collect node entries and their asset files, then
/// <see cref="Save(string)"/> writes the zip container with its <c>manifest.json</c>.
/// </summary>
/// <example>
/// <code>
/// var builder = new OviPackageBuilder("acme/research-pack@1.0.0", "Research Pack")
///     .AddTextFile("agents/researcher.yaml", agentYaml)
///     .AddNode(new PackagedNodeEntry(agentDescriptor, PackagedNodeKind.Agent, "agents/researcher.yaml"));
/// builder.Save("research-pack.ovipkg");
/// </code>
/// </example>
public sealed class OviPackageBuilder
{
    private readonly List<PackagedNodeEntry> _nodes = [];
    private readonly List<PackageReference> _dependencies = [];
    private readonly Dictionary<string, byte[]> _files = new(StringComparer.Ordinal);
    private readonly NodeId _packageId;
    private readonly string _name;
    private readonly string? _description;
    private NodeId? _defaultEntry;

    public OviPackageBuilder(NodeId packageId, string name, string? description = null)
    {
        ArgumentNullException.ThrowIfNull(packageId);
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        _packageId = packageId;
        _name = name;
        _description = description;
    }

    /// <summary>Declares a node carried by this package.</summary>
    public OviPackageBuilder AddNode(PackagedNodeEntry entry)
    {
        ArgumentNullException.ThrowIfNull(entry);
        _nodes.Add(entry with { Path = entry.Path is null ? null : PackagePath.Normalize(entry.Path) });
        return this;
    }

    /// <summary>Adds (or replaces) a file at a package-relative path.</summary>
    public OviPackageBuilder AddFile(string packagePath, byte[] content)
    {
        ArgumentNullException.ThrowIfNull(content);

        var normalized = PackagePath.Normalize(packagePath);
        if (string.Equals(normalized, OviPackageFormat.ManifestEntryName, StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException(
                $"'{OviPackageFormat.ManifestEntryName}' is reserved; the manifest is generated by the builder.",
                nameof(packagePath));
        }

        _files[normalized] = content;
        return this;
    }

    public OviPackageBuilder AddTextFile(string packagePath, string content)
    {
        ArgumentNullException.ThrowIfNull(content);
        return AddFile(packagePath, Encoding.UTF8.GetBytes(content));
    }

    /// <summary>Declares a dependency on another package, by its package id — see <see cref="OviPackageManifest.Dependencies"/>.</summary>
    public OviPackageBuilder AddDependency(NodeId packageId)
    {
        ArgumentNullException.ThrowIfNull(packageId);
        _dependencies.Add(new PackageReference(packageId));
        return this;
    }

    /// <summary>Marks which node entry is this package's default workflow/agent — see <see cref="OviPackageManifest.DefaultEntry"/>.</summary>
    public OviPackageBuilder WithDefaultEntry(NodeId entryId)
    {
        ArgumentNullException.ThrowIfNull(entryId);
        _defaultEntry = entryId;
        return this;
    }

    /// <summary>The manifest as it would be written by <see cref="Save(Stream)"/>.</summary>
    public OviPackageManifest BuildManifest() => new(_packageId, _name, _description)
    {
        Nodes = [.. _nodes],
        Dependencies = [.. _dependencies],
        DefaultEntry = _defaultEntry,
    };

    /// <summary>Writes the package to a stream as a zip archive with a root <c>manifest.json</c>, running <see cref="PackagePublishPipeline.Default"/>.</summary>
    public void Save(Stream destination) => Save(destination, PackagePublishPipeline.Default);

    /// <summary>Writes the package to a stream, running <paramref name="pipeline"/> instead of the default publish steps.</summary>
    public void Save(Stream destination, PackagePublishPipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(destination);
        ArgumentNullException.ThrowIfNull(pipeline);

        using var archive = new ZipArchive(destination, ZipArchiveMode.Create, leaveOpen: true);
        var context = new PackagePublishContext(BuildManifest(), _files, archive);
        pipeline.Run(context);
    }

    /// <summary>Writes the package to a file, conventionally named <c>*.ovipkg</c>, running <see cref="PackagePublishPipeline.Default"/>.</summary>
    public void Save(string path) => Save(path, PackagePublishPipeline.Default);

    /// <summary>Writes the package to a file, running <paramref name="pipeline"/> instead of the default publish steps.</summary>
    public void Save(string path, PackagePublishPipeline pipeline)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        ArgumentNullException.ThrowIfNull(pipeline);

        if (Path.GetDirectoryName(path) is { Length: > 0 } directory)
        {
            Directory.CreateDirectory(directory);
        }

        using var stream = new FileStream(path, FileMode.Create, FileAccess.Write);
        Save(stream, pipeline);
    }
}
