using System.IO.Compression;
using System.Text;
using Ovi.Sdk.Nodes;

namespace Ovi.Sdk.Packaging;

/// <summary>
/// Authors <c>.ovipkg</c> packages: collect node entries and their asset files, then
/// <see cref="Save(string)"/> writes the zip container with its <c>manifest.json</c>.
/// </summary>
/// <example>
/// <code>
/// var builder = new OviPackageBuilder("acme/research-pack@1.0.0", "Research Pack")
///     .AddTextFile("agents/researcher.yaml", agentYaml)
///     .AddNode(new PackagedNodeEntry(agentDescriptor, PackagedNodeKind.Agent, "agents/researcher.yaml"));
/// builder.Save("research-pack.ovipkg");
/// </code>
/// </example>
public sealed class OviPackageBuilder
{
    private readonly List<PackagedNodeEntry> _nodes = [];
    private readonly Dictionary<string, byte[]> _files = new(StringComparer.Ordinal);
    private readonly NodeId _packageId;
    private readonly string _name;
    private readonly string? _description;

    public OviPackageBuilder(NodeId packageId, string name, string? description = null)
    {
        ArgumentNullException.ThrowIfNull(packageId);
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        _packageId = packageId;
        _name = name;
        _description = description;
    }

    /// <summary>Declares a node carried by this package.</summary>
    public OviPackageBuilder AddNode(PackagedNodeEntry entry)
    {
        ArgumentNullException.ThrowIfNull(entry);
        _nodes.Add(entry with { Path = entry.Path is null ? null : PackagePath.Normalize(entry.Path) });
        return this;
    }

    /// <summary>Adds (or replaces) a file at a package-relative path.</summary>
    public OviPackageBuilder AddFile(string packagePath, byte[] content)
    {
        ArgumentNullException.ThrowIfNull(content);

        var normalized = PackagePath.Normalize(packagePath);
        if (string.Equals(normalized, OviPackageFormat.ManifestEntryName, StringComparison.OrdinalIgnoreCase))
        {
            throw new ArgumentException(
                $"'{OviPackageFormat.ManifestEntryName}' is reserved; the manifest is generated by the builder.",
                nameof(packagePath));
        }

        _files[normalized] = content;
        return this;
    }

    public OviPackageBuilder AddTextFile(string packagePath, string content)
    {
        ArgumentNullException.ThrowIfNull(content);
        return AddFile(packagePath, Encoding.UTF8.GetBytes(content));
    }

    /// <summary>The manifest as it would be written by <see cref="Save(Stream)"/>.</summary>
    public OviPackageManifest BuildManifest() => new(_packageId, _name, _description)
    {
        Nodes = [.. _nodes],
    };

    /// <summary>Writes the package to a stream as a zip archive with a root <c>manifest.json</c>.</summary>
    public void Save(Stream destination)
    {
        ArgumentNullException.ThrowIfNull(destination);

        var missing = _nodes
            .Where(entry => entry.Path is not null && !_files.ContainsKey(entry.Path))
            .Select(entry => $"{entry.Id} -> {entry.Path}")
            .ToArray();
        if (missing.Length > 0)
        {
            throw new InvalidOperationException(
                $"Node entries reference files that were not added to the package: {string.Join(", ", missing)}.");
        }

        using var archive = new ZipArchive(destination, ZipArchiveMode.Create, leaveOpen: true);

        var manifestEntry = archive.CreateEntry(OviPackageFormat.ManifestEntryName);
        using (var writer = new StreamWriter(manifestEntry.Open(), Encoding.UTF8))
        {
            writer.Write(BuildManifest().ToJson());
        }

        foreach (var (path, content) in _files.OrderBy(pair => pair.Key, StringComparer.Ordinal))
        {
            var entry = archive.CreateEntry(path);
            using var entryStream = entry.Open();
            entryStream.Write(content);
        }
    }

    /// <summary>Writes the package to a file, conventionally named <c>*.ovipkg</c>.</summary>
    public void Save(string path)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);

        if (Path.GetDirectoryName(path) is { Length: > 0 } directory)
        {
            Directory.CreateDirectory(directory);
        }

        using var stream = new FileStream(path, FileMode.Create, FileAccess.Write);
        Save(stream);
    }
}
